### ISSUE TITLE
"WooCommerce Product Bundles – Min/Max Items requires Product Bundles 5.5 or higher."

### ISSUE THREAD

**Issue by nsberrow** [somewherewarm/woocommerce-product-bundles-min-max-items#10]
Hi, getting this warning when installing this plugin:
"WooCommerce Product Bundles – Min/Max Items requires Product Bundles 5.5 or higher."

I have the latest version of the Product Bundles plugin and it works locally for me.

**Comment by franticpsyx** [comment]
Hey @nsberrow 

Are you running this alongside [WooCommerce Product Bundles](https://woocommerce.com/products/product-bundles/)? 

The current version is 5.14.2.

See https://github.com/somewherewarm/woocommerce-product-bundles-min-max-items/blob/master/woocommerce-product-bundles-min-max-items.php#L75 -- don't see an issue there.
