### ISSUE TITLE
Bundles Min Max items not functioning Woo Cart blocks

### ISSUE THREAD

**Issue by BritishTaste** [somewherewarm/woocommerce-product-bundles-min-max-items#11]
Hi, I’m running the latest version of WooCommerce, Bundles and Min Max on my site: Https://britishtaste.com.br I have a bungled product that forces the customer to buy five products to receive a discount. The min/max functionality works great in the shop, but in the cart I can change the quantity of the products in the cart to what ever I want to and still get the discounted price.

**Comment by franticpsyx** [comment]
Hey @BritishTaste -- 

I have tried to replicate this locally without any luck. This is what you should be seeing: https://a.cl.ly/nOukmyL8

It's likely that your theme (or another plugin) is overriding the default WooCommerce cart validation, and in the process preventing other plugins from validating changes. To confirm:

<ol>
<li>Temporarily switch back to a default WordPress theme (or Storefront). If this resolves the issue, then please bring this to the attention of your theme author.</li>
<li>If the issue persists, then disable all other plugins except for WooCommerce and extension. If this fixes the issue, then slowly re-enable plugins until you find the one that triggers it.</li>
</ol>

Closing this one as ​we haven't had any similar issue reports sent to us over the last few years -- we also use a number of real-world test cases in day-to-day development workflow and haven't noticed anything similar.
