### ISSUE TITLE
Bundled products using Min/ Max items do not work with WOO Shopping Basket Block

### ISSUE THREAD

**Issue by BritishTaste** [somewherewarm/woocommerce-product-bundles-min-max-items#12]
Hey @BritishTaste -- 

I have tried to replicate this locally without any luck. This is what you should be seeing: https://a.cl.ly/nOukmyL8

It's likely that your theme (or another plugin) is overriding the default WooCommerce cart validation, and in the process preventing other plugins from validating changes. To confirm:

<ol>
<li>Temporarily switch back to a default WordPress theme (or Storefront). If this resolves the issue, then please bring this to the attention of your theme author.</li>
<li>If the issue persists, then disable all other plugins except for WooCommerce and extension. If this fixes the issue, then slowly re-enable plugins until you find the one that triggers it.</li>
</ol>

Closing this one as ​we haven't had any similar issue reports sent to us over the last few years -- we also use a number of real-world test cases in day-to-day development workflow and haven't noticed anything similar.

_Originally posted by @franticpsyx in https://github.com/somewherewarm/woocommerce-product-bundles-min-max-items/issues/11#issuecomment-671331960_

**Comment by BritishTaste** [comment]
Hi @franticpsyx,

Appologies, I forgot to mention a crtical piece of info. The is with Min / Max Product bundles using **WooCommerce Shopping Cart block**  Please see the document that shows what's happening. [https://1drv.ms/b/s!AqMW_7rzd1eJgc5SnWm3keWjLDg18A?e=hfGXoV](url)

**Comment by franticpsyx** [comment]
Hey there, the WooCommerce Cart Block is still in beta and has many known issues with a number of plugins out there :)
