### ISSUE TITLE
Not allowing to add product

### ISSUE THREAD

**Issue by christianswanepoel** [somewherewarm/woocommerce-product-bundles-min-max-items#13]
The plugin correctly prevents adding more than max(3), and less than min(3), but when I click "Add to cart" it displays an error - "XXX" cannot be added to your cart. "XXX" cannot be purchased. 

### SETTINGS
Items Required (≥) 3
Items Allowed (≥) 3

Each Product:
Optional true
Quantity min 0
Quantity max 3
Shipped/Priced Individually false

### VERSIONS
woocommerce-product-bundles-min-max-items - Version 1.4.3
woocommerce - Version 4.6.2
WooCommerce Product Bundles - Version 6.2.5

**Comment by christianswanepoel** [comment]
Noob mistake! The product is set as "Hidden" and therefore clearly not purchasable.

**Comment by manospsyx** [comment]
Hey thanks for the update @christianswanepoel -- I was going to get to your message in a few minutes, looks like you got here first!
