### ISSUE TITLE
Does not work in cart

### ISSUE THREAD

**Issue by victor-e-claeys** [somewherewarm/woocommerce-product-bundles-min-max-items#3]
This plugin works great when on the product but does not validate quantities that are changed in the cart.

**Comment by franticpsyx** [comment]
Confirmed :) PB cart quantities are editable since version 5.5, which was just released. We need to add support for this in Min/Max Items.

**Comment by franticpsyx** [comment]
closed in 2d6b3619da5636e26dfbfd6e1a867a9dd4b57b25
