### ISSUE TITLE
set a default amount per item in bundle

### ISSUE THREAD

**Issue by stephansperling** [somewherewarm/woocommerce-product-bundles-min-max-items#9]
Hey!
Great plugin, thanks a lot!
There is one little feature that would make me even more happy:
We'd like to set default amounts per bundled item so the user does not start with a "0". So we can propose a perfect mix of bundled items and customers who do not want the change this default configuration can place their order much quicker. 
Maybe you can add this feature at some point?

Best regards!

Stephan

**Comment by franticpsyx** [comment]
Hey @stephansperling thanks for the feedback!

Feel free to up-vote this idea at http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/19856386-add-default-quantity-on-a-product-bundle

Closing here as this request shouldn't limited to the Min/Max Items mini-extension.
